spring:
  profiles:
    active: test
    group:
      local: local, common
      test: test, common
      prod: common, prod, auth, prod-db
---
# common 환경
spring:
  config:
    activate:
      on-profile: common

---
# test 환경
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE  # db ?? ??
  sql:
    init:
      data-locations: classpath:data.sql # ???? ???? script
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true # hibernate? ????? ? data.sql ???? ?? ??
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
logging:
  level:
    root: DEBUG
    org:
      springframework:
        security: DEBUG